### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by qbzzt**
availabe -> available

### CODE REVIEW

**Review by annieke — APPROVED** [review]
Omg Ori!

**Review by smartcontracts — APPROVED** [review]

**Comment by smartcontracts** [comment]
tyy

**Comment by qbzzt** [comment]
Nice to "meet" y'all. I wish I could meet you in Istanbul, but due to the political situation I decided it's best for people whose passport says they were born in Israel not to go there.

I like the new docs site.

**Comment by F3n4nd0gm** [comment]
Is & cripto

**Comment by F3n4nd0gm** [comment]
Solana

**Pull request merged**
