### PR TITLE
Add another snapshot provider

### PR DESCRIPTION
**Pull request by ynvv**
**Description**

Hello! I am Artem from fastnode.io
We are aware of the community's concerns about the lack of fresh op-geth snapshots - we already have an extensive number of internal snapshots, which we are ready to share with the OP community!

We are ready to update them every week so that community can raise nodes in a few hours, not in a few weeks.

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by Chomtana** [comment]
TLDR: Fastnode provided an alternative OP mainnet snapshot solution >> https://datapoint.fastnode.io/

Thank you for providing an OP mainnet snapshot. Would like to know if we can have an endpoint that dynamically fetch the latest snapshot file name.

**Comment by pires** [comment]
This would be helpful for Sepolia too. Do you run on said network? 🙏🏻

**Comment by sbvegan** [comment]
This is awesome, thank you for providing this service. My only suggestion is around the wording and highlighting that this is a third party provided snapshot.

**Comment by Chomtana** [comment]
Look like this archive extract to a folder named op-dir with geth inside. It would be better to extract to only geth folder (no op-dir wrapper) as the official snapshot has this behavior.

**Comment by cpengilly** [comment]
@ynvv I have made the suggested changes as requested by @sbvegan but if you could please address the comment by @Chomtana I'd be grateful 🙏🏾 😄

**Comment by felipe-op** [comment]
@Chomtana I'm having trouble downloading the full file - can you please share what the directory structure looks like?
i.e. `tree -d` in the decompressed directory

**Comment by smartcontracts** [comment]
I'd also like to change this PR so that it changes the snapshots.mdx page instead. I'll modify the tutorial to point to that page. I'm going to make a PR to update the snapshots.mdx page with the correct format so you can add your link(s).

**Comment by Chomtana** [comment]
image

@felipe-op Like this it's wrapped in an op-dir folder while the correct one should extract directly to the geth folder

You should be able to use `aria2c` to download and use

```
tar --use-compress-program=lz4 -xf filename.tar.lz4
```

to extract file

Like this
* https://github.com/Chomtana/simple-optimism-node/blob/snapshot-fastnode/scripts/init-bedrock.sh
* https://github.com/Chomtana/simple-optimism-node/blob/snapshot-fastnode/scripts/utils.sh

**Comment by sbvegan** [comment]
Hey @ynvv would you be able to update the directory structure to address the comment above?

Hey @cpengilly and @smartcontracts, what do you guys think about adding a callout for the correct directory structure so we can get this PR in now? I have folks asking for full node snapshots and I'm directing them to this PR instead of the docs.

**Comment by ynvv** [comment]
Hello, guys!

We will upload a new snapshot soon, which will contain all the edits that were discussed here. There will also be a permanent link to the latest snapshot

**Comment by ottomakan** [comment]
@ynvv Does this snapshot include the activation? I see it is dated 12-16-2023 so just wondering? Thanks for doing this!

**Comment by Sleapy31** [comment]
Thank you that snapshot worked for me !
The snapshot from the documentation (who is outdated) was not working and I could not even launch op-geth because of 'block bodies error'

**Comment by ynvv** [comment]
Hello, guys!
We're just uploaded new snapshot with latest block [115039006](https://optimistic.etherscan.io/block/115039006) (after network update - Jan-19-2024 03:06:29 PM +UTC) at our site [datapoint.fastnode.io](https://datapoint.fastnode.io)

We have changed the structure of the archive: now only the geth folder is inside the archive (without the op-volume folder)

We also added the ability to download the first up-to-date snapshot of all that we have (details on the website above) (@Chomtana for u)

**Comment by sbvegan** [comment]
@Sleapy31 which snapshot didn't work for you?
Screenshot 2024-01-19 at 11 33 22 AM

**Comment by Sleapy31** [comment]
> @Sleapy31 which snapshot didn't work for you? Screenshot 2024-01-19 at 11 33 22 AM

OP Mainnet (Full Node) despite the checksum being correct.

**Comment by sbvegan** [comment]
@Sleapy31 okay thats weird, I imagine it was something else that caused the errors because that snapshot has worked for others spinning up OP Mainnet nodes. If you have questions like this in the future, you can direct them to our forum and we can help you answer them. https://github.com/ethereum-optimism/developers/discussions

**Review by cpengilly — APPROVED** [review]

**Pull request merged**
