### PR TITLE
Update rpc-providers.mdx

### PR DESCRIPTION
**Pull request by 4everlandorg**
Add 4everland RPC service to rpc-paovider list.

**Description**

Add 4everland RPC service to rpc-paovider list. 
More info about this services: https://docs.4everland.org/rpc-beta/guides

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Review by cpengilly — APPROVED** [review]
@4everlandorg thank you for your contribution!

**Comment by cpengilly** [comment]
@4everlandorg you'll need to resolve linting issues in order to merge PR. you can run `pnpm fix` to automatically fix most linting issues, see the [contributing.md](https://github.com/ethereum-optimism/docs/blob/main/CONTRIBUTING.md#send-pull-request) file for more details 😄

**Comment by smartcontracts** [comment]
It looks like "EVERLAND" is failing because of the spellcheck. Please add EVERLAND to the words.txt file in the root of this repository!

**Comment by cpengilly** [comment]
@4everlandorg so sorry for the oversight! I updated the words.txt file and captured this process in our contributing.md file for future contributors. If you could please merge changes from main into your branch, this should resolve the issue. 🙏🏾 😄

**Comment by 4everlandorg** [comment]
> @4everlandorg so sorry for the oversight! I updated the words.txt file and captured this process in our contributing.md file for future contributors. If you could please merge changes from main into your branch, this should resolve the issue. 🙏🏾 😄

Thanks! I've finished syncing.

**Comment by cpengilly** [comment]
@4everlandorg sorry, it looks like "ELIFECYCLE" also needs to be added to words.txt file too

**Comment by cpengilly** [comment]
@4everlandorg i apologize, but can you resync again? please run `pnpm spellcheck` to make sure there are no issues before sending the PR again 🙏🏾

**Comment by cpengilly** [comment]
might also run `pnpm install` to ensure all dependencies are installed :)

**Pull request closed without merging**
