### PR TITLE
Add Granite to network upgrades page.

### PR DESCRIPTION
**Pull request by pauldowman**
Adds Granite hard fork times to the network upgrades page. 

This PR is not ready yet because I noticed that there are broken anchor links to specs/superchain-upgrades.html, e.g. https://specs.optimism.io/protocol/superchain-upgrades.html#fjord, and there are pages in the specs repo for each hard fork that should probably be linked to instead but the granite page isn't ready.

### CODE REVIEW

**Comment by pauldowman** [comment]
So questions (some are about the specs repo):

1. Should this page in dcos be linking to the specific hard fork page in specs? Right now it has a lot of links to the superchain upgrades page.
2. Should there be a PR on specs to update the Granite page?
3. Should it be linked in the sidebar? I see there are other hard fork pages that also aren't linked there
4. The superchain upgrades page in specs also has a footnote for Granite that "Governance vote and veto still have to pass".

**Comment by pauldowman** [comment]
I made a PR in specs to add the Granite page to the sidebar and changed all hard fork specs links to go to their details page: https://github.com/ethereum-optimism/specs/pull/367

**Comment by sbvegan** [comment]
Hey @pauldowman thanks for opening this PR. Our team will take a look but we're a short staffed this week so it might take a couple days

**Review by bradleycamacho — APPROVED** [review]

**Comment by bradleycamacho** [comment]
We can merge once the specs PR is merged

**Comment by pauldowman** [comment]
Thanks @bradleycamacho! The specs PR is merged now. Should I merge this or is that usually for someone on the docs team to do??

**Pull request merged**
