### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by cpengilly**
fix broken links on PRs

### CODE REVIEW

**Comment by sbvegan** [comment]
The EAS links seem to be red herrings, but can we figure out how to fix the JSON file its complaining on?

**Comment by cpengilly** [comment]
@sbvegan not sure how to resolve the json error, but I'll research more and see if we can get it resolved

**Comment by sbvegan** [comment]
@cpengilly i wonder if this is something that needs to be fixed on the backend. The file path in the error looks funky.

**Review by sbvegan — APPROVED** [review]
I'm going to approve this one to fix the other broken links, but I think we should log an issue to fix lychee on this json file in the public directory

**Pull request merged**
