### PR TITLE
modify admin account suggest balance when deploy your own testnet

### PR DESCRIPTION
**Pull request by withzoo**
Cost as follows when deploying rollup testnet on sepolia:

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.337178127660167352 ETH (34101896 gas * avg 10.038510876 gwei)

### CODE REVIEW

**Comment by withzoo** [comment]
> Guess gas prices on Sepolia are increasing now that Goerli is shutting down :-(
> 
> Would you mind setting this to 0.5 just to be safe?

**Comment by withzoo** [comment]
> Guess gas prices on Sepolia are increasing now that Goerli is shutting down :-(
> 
> Would you mind setting this to 0.5 just to be safe?

Of course, it's safer, already modify

**Review by cpengilly — APPROVED** [review]

**Comment by cpengilly** [comment]
@coderabbitai review

**Comment by smartcontracts** [comment]
@withzoo can you rebase this PR on top of the latest `main`?

**Comment by smartcontracts** [comment]
Hi, for some reason there's an issue with github actions on this PR, I'm going to open up a new PR for this instead.

**Pull request closed without merging**
