### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by cpengilly**
add node squad to code owners :)

### CODE REVIEW

**Review by sbvegan — COMMENTED** [review]
it looks like node-squad is a subset of engineering teams, so you might need to update it to include engineering in the path

**Comment by sbvegan** [comment]
you probably also have to give absolute paths to the sections and follow it with a wildcard

here's the codeowners doc: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by cpengilly** [comment]
@sbvegan I'm clearly new at this, so please bare with me 😆 
1. For the file paths, I followed the git instructions which was written like this:
```
# In this example, any change inside the `/scripts` directory
# will require approval from @doctocat or @octocat.
/scripts/ @doctocat @octocat
```
2. And for the team name, I used the same format as `@ethereum-optimism/docs-reviewers` because it is also nestled inside another team (devrel) but not reflected in the name/path `ethereum-optimism > teams > devrel > docs-reviewers`

**Comment by cpengilly** [comment]
I guess it would help if there was a way to test it out??

**Review by sbvegan — APPROVED** [review]

**Pull request merged**
