### PR TITLE
Algolia search

### PR DESCRIPTION
**Pull request by alvesjtiago**
**Description**

This is an implementation of Algolia search using the same primitives as Nextra native search as described on the Algolia Search Bounty - https://oplabs.notion.site/Algolia-Search-Bounty-Spec-b36573a3d36643c4b40eb6568b476f44.

Environment variables required (can be changed later for a dedicated project if necessary):

```
NEXT_PUBLIC_ALGOLIA_APP_ID="ECJ5AHC7GY"
NEXT_PUBLIC_ALGOLIA_API_KEY="ebbdaf91def1c90ace0727f95a77c224"
NEXT_PUBLIC_ALGOLIA_INDEX="algolia"
```

This implementation maintains the same Nextra native search and extends it to support Algolia.
The Algolia indexer is broken down into multiple sections of the same document for finer search and the script is included in order to run it as part of the pipeline whenever necessary.

In order to test it, please add the above environment variables to the pipeline or to your local `.env` file.

*Note: I believe there is space for improvement but since the deadline is tomorrow I wanted to submit a working implementation that can be improved in further PR's or commits if necessary.*

**Tests**

Manual tests were conducted and sharing some screenshots below:

Screenshot 2024-06-27 at 20 03 10
Screenshot 2024-06-27 at 20 02 57

**Additional context**

This is a submission in response to the bounty from Bountycaster - https://www.bountycaster.xyz/bounty/0x953ba9472714d4c20183c30f47df9ae7266c4a20

### CODE REVIEW

**Comment by cpengilly** [comment]
@alvesjtiago Thanks for the submission! We experience an error when trying to run locally and in deploy preview (tried on two diff machines/setups). Can you help resolve, so we can resume testing? 🙏🏾 💟 
error-algolia

**Comment by alvesjtiago** [comment]
I'm so sorry about that @cpengilly. I'm trying to reproduce that issue on my end but I haven't been able to do it yet.

The deploy preview (https://deploy-preview-773--docs-optimism.netlify.app/) also seems to be loading fine (with the caveat it doesn't have the env variables setup). You mentioned that you were able to reproduce it there, can you tell me how?

Also, happy to move the env variables directly into the code and have them committed but I imagine these would be migrated to another account at some point so wanted to make it configurable. Let me know what would be preferred.

Thank you and apologies once again!

**Comment by alvesjtiago** [comment]
From the previous commit, I just saw that you added an `.env.example` file but it should actually be `.env`. Are you able to try with that @cpengilly? Thank you!

**Comment by cpengilly** [comment]
@alvesjtiago My apologies, the error was in local env -- reproduced by @sbvegan too. The deploy preview didn't show an error -- it just didn't' provide any search results

**Comment by cpengilly** [comment]
> From the previous commit, I just saw that you added an `.env.example` file but it should actually be `.env`. Are you able to try with that @cpengilly? Thank you!

yes, I removed the .example from the .env file but still had the error

**Comment by alvesjtiago** [comment]
Were you able to get it running now? I'm happy to replace directly in the code the contents of `.env` since that seems to be the source of the issue.

**Comment by sbvegan** [comment]
@alvesjtiago I hardcoded the values directly without the environment variables and got the same result as Cynthia when I tried to build it locally.

**Comment by alvesjtiago** [comment]
That is very strange, I'm happy to jump on a call @sbvegan and @cpengilly  if needed to understand what's happening on your local machines. Meanwhile I've hardcoded the values to the repo and it's successfully running on the deploy preview - https://deploy-preview-773--docs-optimism.netlify.app/

**Comment by sbvegan** [comment]
@alvesjtiago sorry I'm in a call right now, but I think the issue was because we were using the search api key, project id, and index from our algolia dashboard. When we were testing a different implementation it didn't actually generate the index file with the command you included in the `package.json`: 

```
"index:docs": "npx ts-node --skip-project utils/algolia-indexer.ts",
```

I imagine this is the source of the inconsistency with what you have locally and being deployed in the preview. For every new change, would we need to update the `algolia.json` on the dashboard each time?

**Comment by alvesjtiago** [comment]
@sbvegan indexing for Algolia can be done in two ways (there's more ways but describing the two I consider best):
- Paid service like Algolia Crawler
- `index:docs` command integrated into Github flows

The advantages of Algolia Crawler is that it's automatic and can integrate with Netlify but it has several limitations:
- Limit of 100 max crawled URL's 
- Not able to access source code for `.mdx` data
- Delay between deploy and crawl
- Less configurability on index structure
- Paid

The command created needs to be implemented via Github actions to send upon deployment but after it's setup it does not require Algolia Crawler.

The current frontend implementation accepts both and it's not tied to one or the other. I'm happy to setup the Github action for the `index:docs` command or setup Algolia Crawler in a production account.

The `algolia.json` file is not necessary and it's just an intermediate product of the script in order to upload it to Algolia.

Let me know if it was clear or if you have any questions.

**Comment by cpengilly** [comment]
@alvesjtiago when I was testing, I tried to change env variables in the [index.tsx](https://github.com/ethereum-optimism/docs/pull/773/files#diff-29ddaf5fb3d6e2e650e13686b29a944587795beeed4e1273b7056435167a1b54) as @sbvegan mentioned and that's when I ran into problems. I tried to change these lines specifically:
> const client = algoliasearch("ECJ5AHC7GY", "ebbdaf91def1c90ace0727f95a77c224");
> const index = client.initIndex("algolia");

to be something like:

> const client = algoliasearch("P7A16UOSI5", "702dd042cad3dfd9581e362b36033291");
> const index = client.initIndex("optimism"); 

I'm not as technical as @sbvegan so we'll likely have to wait until the week of 7/8 to get this resolved (the whole company is on holiday/collective pause next week). Just wanted to give a bit more context on our end; have a wonderful weekend, and we'll be in touch in a couple of weeks 💟

**Comment by alvesjtiago** [comment]
Ah got it @cpengilly! So that's likely because of the structure of the index that I have setup. As you can see on the screenshot below it is using `slug`, `title` and `description`. Probably the names are different on your index and hence why it's failing.

Screenshot 2024-06-29 at 16 42 23

If I know the structure of your indexed info I can adapt it on the PR and on the index I created. Would you be able to share this info for the `optimism` index mentioned above? Thank you!

**Comment by cpengilly** [comment]
@alvesjtiago So sorry for the delay. We were on holiday last week. Perhaps I can add you to our algolia account temporarily -- would you mind sharing your email?

**Comment by alvesjtiago** [comment]
@cpengilly no problem at all, of course. Do you mind if I share via X / Twitter DM's or some other way that is not so public that works for you? Thank you!

**Comment by cpengilly** [comment]
@alvesjtiago Yes, of course. I'm not on twitter. Here's my telegram handle: https://t.me/cpengilly
Also pinging @sbvegan for twitter, in case you're not on Telegram. 💟

**Comment by cpengilly** [comment]
@alvesjtiago confirmed that you can use this twitter, if it's easier: `soyboy_vegan`

**Comment by alvesjtiago** [comment]
Sorry about the delay! Just messaged you on telegram @cpengilly

**Comment by cpengilly** [comment]
Update: Thank you for the submission! We are still testing the integrations and will be in touch by end of July with all bounty submitters on the results. 💟

**Review by cpengilly — APPROVED** [review]

**Pull request merged**
