### PR TITLE
update getting started documentation

### PR DESCRIPTION
**Pull request by accessor-io**
**Description**
proposed documentation changes of 'getting started' sourced from [Kleoverse bounty post](https://kleoverse.com/bounty/7f834985-f91e-47c4-8692-a91245475825) in ref. to [Issue #202](https://github.com/ethereum-optimism/docs/issues/202) posted by @cpengilly.

**Additional context**
Link to style guide under .../contribute returned a [404](https://github.com/ethereum-optimism/docs/blob/91f929a65aa84c8919a1d43bd65038d5e1dc5119/pages/contribute/style-guide.mdx). Referencing previous commits, style for '.mdx' should be correct.

notated actions and request for review and pull notated in [Issue #202](https://github.com/ethereum-optimism/docs/issues/202) comments.

### CODE REVIEW

**Review by Anton-dot911 — APPROVED** [review]

**Review by Anton-dot911 — APPROVED** [review]

**Review by accessor-io — COMMENTED** [review]
request update

**Comment by smartcontracts** [comment]
@coderabbitai review

**Comment by cpengilly** [comment]
Hi @accessor-io! thank you for sending a PR. We like to keep the PRs tightly focused around a single item/task, so if you could please separate the CEX changes from the getting started changes, I would greatly appreciate it. 
- Your CEX changes are awesome and we can merge those changes when the new PR comes thru. Thanks for the work on that and the detailed instructions you added to the page 🥇 
- We decided to go in a different direction for the getting started page, so please hold off on a new PR for that content right now. I have removed it as a good first issue while I work on scoping and clarifying the request more. 💟

**Comment by accessor-io** [comment]
okay!
________________________________

**Comment by accessor-io** [comment]
what is going  on with this
Screenshot from 2023-12-31 08-23-40
Screenshot from 2023-12-31 08-22-46
Screenshot from 2023-12-31 08-22-46
Screenshot from 2023-12-31 08-22-28

**Comment by accessor-io** [comment]
i've not seen these workflows before. very confusing directions. sorry late reply.

**Comment by cpengilly** [comment]
@accessor-io we've added several new features to docs since the original PR, so you might be missing dependencies now. I suggest branch conflicts, run `pnpm install`, then `pnpm lint` to fix errors. hopefully that resolves the issues in the PR 💟

**Comment by cpengilly** [comment]
closing due to no response

**Pull request closed without merging**
