### PR TITLE
added Supra to oracles.mdx

### PR DESCRIPTION
**Pull request by ksdumont**
**Description**

Supra recently deployed our Oracle to Optimism mainnet. I added Supra's information to your oracles.mdx file in the documentation.

### CODE REVIEW

**Comment by cpengilly** [comment]
@ksdumont thank you for submitting a PR! Please resolve the linting issues in order to merge PR. You can run `pnpm fix` to automatically fix most linting issues, see the [contributing.md](https://github.com/ethereum-optimism/docs/blob/main/CONTRIBUTING.md#send-pull-request) file for more details 🙏🏾 😄

**Comment by ksdumont** [comment]
Hi, I just ran the command. Kindly let me know when it is merged, thank you!

**Comment by cpengilly** [comment]
@ksdumont I apologize for the oversight! The linting is still failing due to spellcheck, so I updated the words.txt file and captured this process in our contributing.md file for future contributors. If you could please merge changes from main into your branch, this should resolve the issue. 🙏🏾 😄

**Comment by ksdumont** [comment]
Hi @cpengilly - I just merged the changes as you requested. Kindly let me know when it is merged.

**Comment by ksdumont** [comment]
Hi @cpengilly, could we have our oracle info added to this page as well, like all of the other oracles, https://docs.optimism.io/builders/tools/oracles

**Pull request closed without merging**
